### ISSUE TITLE
Error: Cannot find module './TextBlockWithImage.js'

### ISSUE THREAD

**Issue by Incogner** [agility/agilitycms-nextjs-starter#19]
I have recently created a free account on agilityCMS portal and copied this repo to run on local env. But after running npm install, npm run predev, and npm run dev, I see error -> Error: Cannot find module './TextBlockWithImage.js'. I am sure there is content missing in the repository that is already published on agility, I created a dummy file with the above name in the agility-modules folder, this error resolved, however, I do not know how to create the missing module.
Anyways, after putting the dummy module, I see another error ->
![image](https://user-images.githubusercontent.com/36832557/119565044-75cc1900-bd77-11eb-8448-aab784758c32.png)

Please let me know if I can resolve these issues or should I wait until the next release.
Thanks

**Comment by joshua-isaac** [comment]
hey @Incogner!

It looks like you cloned this starter: https://github.com/agility/agilitycms-nextjs-starter-2020 (deprecated next.js starter)

instead of this starter: https://github.com/agility/agilitycms-nextjs-starter (latest next.js starter)
