### ISSUE TITLE
How to add pagination?

### ISSUE THREAD

**Issue by fishermanlok169** [agility/agilitycms-nextjs-starter#23]
Hi there, I found it very hard to add pagination to the site. A few things are blocking me:
1. No access to query string in getCustomInitialProps.
2. Cannot sort with api.getContentList because it's using the sync sdk. 
3. Lack of docs / guides in the community.

This becomes more serious because `getContentList` can only take at most 50 elements and our site have a lot more than that. 

It would be great if someone can point me some directions.

**Comment by jamesvidler** [comment]
@joshua-isaac could you take a look at this? May be good to include an example of how to do this in the starter.

**Comment by joshua-isaac** [comment]
@fishermanlok169 Hi there,

I just wrote a tutorial on how you can implement Pagination in our Next.js starter using the Skip & Take parameters. This example is using the REST API however: https://agilitycms.com/docs/nextjs/implementing-pagination-with-next-js

I hope this helps.
